# Generated by Django 4.0.6 on 2024-04-16 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcurso', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplina',
            old_name='curricular_unit_readable_code',
            new_name='curricularIUnitReadableCode',
        ),
    ]
