# Generated by Django 4.0.6 on 2024-04-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcurso', '0003_alter_disciplina_linguagens_alter_projeto_linguagens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='linguagens',
            field=models.ManyToManyField(blank=True, null=True, to='appcurso.linguagemdeprogramacao'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='linguagens',
            field=models.ManyToManyField(blank=True, null=True, to='appcurso.linguagemdeprogramacao'),
        ),
    ]
