# Generated by Django 4.0.6 on 2024-04-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcurso', '0004_alter_disciplina_linguagens_alter_projeto_linguagens'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='curso_capa/'),
        ),
    ]
