# Generated by Django 4.0.6 on 2024-04-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='festival_images/'),
        ),
    ]
