# Generated by Django 4.0.6 on 2024-04-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0002_festival_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
