# Generated by Django 4.0.6 on 2024-03-19 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='fotos_banda')),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_link', models.URLField(blank=True, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('tempo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capa', models.ImageField(upload_to='album_capas/')),
                ('nome', models.CharField(max_length=100)),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albuns', to='bandas.banda')),
                ('musicas', models.ManyToManyField(related_name='musicas', to='bandas.musica')),
            ],
        ),
    ]
