# Generated by Django 4.0.6 on 2024-03-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='capa',
            field=models.ImageField(upload_to='album_covers/'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='foto',
            field=models.ImageField(upload_to='band_photos/'),
        ),
    ]
