# Generated by Django 4.0.6 on 2024-04-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0002_alter_album_capa_alter_banda_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='capa',
        ),
        migrations.RemoveField(
            model_name='banda',
            name='foto',
        ),
        migrations.AddField(
            model_name='album',
            name='ano_lancamento',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='banda',
            name='ano_criacao',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='banda',
            name='nacionalidade',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
