# Generated by Django 4.0.6 on 2024-04-16 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0003_remove_album_capa_remove_banda_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='banda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albuns', to='bandas.banda'),
        ),
    ]
