# Generated by Django 4.0.6 on 2024-04-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0007_alter_banda_id_alter_musica_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='capa',
        ),
        migrations.RemoveField(
            model_name='album',
            name='musicas',
        ),
        migrations.AddField(
            model_name='album',
            name='faixas',
            field=models.ManyToManyField(related_name='albums', to='bandas.musica'),
        ),
    ]
