# Generated by Django 4.0.6 on 2024-04-18 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0008_remove_album_capa_remove_album_musicas_album_faixas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='faixas',
            new_name='musicas',
        ),
    ]
