# Generated by Django 4.0.6 on 2024-04-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0009_rename_faixas_album_musicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='capa',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='capas'),
        ),
    ]
