# Generated by Django 4.0.6 on 2024-04-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0011_alter_musica_tempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='spotify_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
