# Generated by Django 4.0.6 on 2024-05-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0012_alter_musica_spotify_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='musicas',
            field=models.ManyToManyField(blank=True, null=True, related_name='albums', to='bandas.musica'),
        ),
    ]
