# Generated by Django 4.0.6 on 2024-05-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0014_banda_biografia_musica_letra'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='foto',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='fotos'),
        ),
    ]
