# Generated by Django 4.0.6 on 2024-04-17 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogues.autor'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artigos_autor', to='blogues.autor'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='artigos',
            field=models.ManyToManyField(related_name='categorias', to='blogues.artigo'),
        ),
    ]
