# Generated by Django 4.0.6 on 2024-04-17 16:30

import blogues.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogues', '0003_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='artigos',
            field=models.ManyToManyField(blank=True, null=True, related_name='categorias', to='blogues.artigo'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='autor',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogues.autor'),
        ),
    ]
