# Generated by Django 4.0.6 on 2024-04-17 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogues', '0004_alter_categoria_artigos_alter_rating_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blogues.autor'),
        ),
    ]
