# Generated by Django 4.0.6 on 2024-04-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogues', '0005_alter_rating_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
